name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image zabbix server add odbc
      run: docker build . --file Dockerfile --tag tomornb/zabbix_server_mysql:5_2_odbc
	  